// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.scripts_integration.Domestic.eSubscriptionPurchase.eSubscriptionBNWallet;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC02_eSubPurchaseUK</b><br>
 * Generated     : <b>2014/10/03 11:27:26 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  October 03, 2014
 * @author zsadeque
 */
public abstract class TC02_eSubPurchaseUKHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point BNSubcriptionRelCreated object in the SUT.
	 */
	protected IFtVerificationPoint BNSubcriptionRelCreatedVP() 
	{
		return vp("BNSubcriptionRelCreated");
	}
	protected IFtVerificationPoint BNSubcriptionRelCreatedVP(TestObject anchor)
	{
		return vp("BNSubcriptionRelCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point BNSubcriptionRelGotCreated object in the SUT.
	 */
	protected IFtVerificationPoint BNSubcriptionRelGotCreatedVP() 
	{
		return vp("BNSubcriptionRelGotCreated");
	}
	protected IFtVerificationPoint BNSubcriptionRelGotCreatedVP(TestObject anchor)
	{
		return vp("BNSubcriptionRelGotCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point CCAuthorization object in the SUT.
	 */
	protected IFtVerificationPoint CCAuthorizationVP() 
	{
		return vp("CCAuthorization");
	}
	protected IFtVerificationPoint CCAuthorizationVP(TestObject anchor)
	{
		return vp("CCAuthorization", anchor);
	}
	
	/**
	 * Locate and return the verification point EDSLocker object in the SUT.
	 */
	protected IFtVerificationPoint EDSLockerVP() 
	{
		return vp("EDSLocker");
	}
	protected IFtVerificationPoint EDSLockerVP(TestObject anchor)
	{
		return vp("EDSLocker", anchor);
	}
	
	/**
	 * Locate and return the verification point EDSService object in the SUT.
	 */
	protected IFtVerificationPoint EDSServiceVP() 
	{
		return vp("EDSService");
	}
	protected IFtVerificationPoint EDSServiceVP(TestObject anchor)
	{
		return vp("EDSService", anchor);
	}
	
	/**
	 * Locate and return the verification point FinalDocFlow object in the SUT.
	 */
	protected IFtVerificationPoint FinalDocFlowVP() 
	{
		return vp("FinalDocFlow");
	}
	protected IFtVerificationPoint FinalDocFlowVP(TestObject anchor)
	{
		return vp("FinalDocFlow", anchor);
	}
	
	/**
	 * Locate and return the verification point InvoicePosted object in the SUT.
	 */
	protected IFtVerificationPoint InvoicePostedVP() 
	{
		return vp("InvoicePosted");
	}
	protected IFtVerificationPoint InvoicePostedVP(TestObject anchor)
	{
		return vp("InvoicePosted", anchor);
	}
	
	/**
	 * Locate and return the verification point IPResponseVP object in the SUT.
	 */
	protected IFtVerificationPoint IPResponseVPVP() 
	{
		return vp("IPResponseVP");
	}
	protected IFtVerificationPoint IPResponseVPVP(TestObject anchor)
	{
		return vp("IPResponseVP", anchor);
	}
	
	/**
	 * Locate and return the verification point NetPriceAndTax object in the SUT.
	 */
	protected IFtVerificationPoint NetPriceAndTaxVP() 
	{
		return vp("NetPriceAndTax");
	}
	protected IFtVerificationPoint NetPriceAndTaxVP(TestObject anchor)
	{
		return vp("NetPriceAndTax", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderOpen object in the SUT.
	 */
	protected IFtVerificationPoint OrderOpenVP() 
	{
		return vp("OrderOpen");
	}
	protected IFtVerificationPoint OrderOpenVP(TestObject anchor)
	{
		return vp("OrderOpen", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderProcessed object in the SUT.
	 */
	protected IFtVerificationPoint OrderProcessedVP() 
	{
		return vp("OrderProcessed");
	}
	protected IFtVerificationPoint OrderProcessedVP(TestObject anchor)
	{
		return vp("OrderProcessed", anchor);
	}
	
	/**
	 * Locate and return the verification point PartnersTable object in the SUT.
	 */
	protected IFtVerificationPoint PartnersTableVP() 
	{
		return vp("PartnersTable");
	}
	protected IFtVerificationPoint PartnersTableVP(TestObject anchor)
	{
		return vp("PartnersTable", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreated object in the SUT.
	 */
	protected IFtVerificationPoint POCreatedVP() 
	{
		return vp("POCreated");
	}
	protected IFtVerificationPoint POCreatedVP(TestObject anchor)
	{
		return vp("POCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreation object in the SUT.
	 */
	protected IFtVerificationPoint POCreationVP() 
	{
		return vp("POCreation");
	}
	protected IFtVerificationPoint POCreationVP(TestObject anchor)
	{
		return vp("POCreation", anchor);
	}
	
	/**
	 * Locate and return the verification point SalesData object in the SUT.
	 */
	protected IFtVerificationPoint SalesDataVP() 
	{
		return vp("SalesData");
	}
	protected IFtVerificationPoint SalesDataVP(TestObject anchor)
	{
		return vp("SalesData", anchor);
	}
	
	/**
	 * Locate and return the verification point SubsSaved object in the SUT.
	 */
	protected IFtVerificationPoint SubsSavedVP() 
	{
		return vp("SubsSaved");
	}
	protected IFtVerificationPoint SubsSavedVP(TestObject anchor)
	{
		return vp("SubsSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point VertexService object in the SUT.
	 */
	protected IFtVerificationPoint VertexServiceVP() 
	{
		return vp("VertexService");
	}
	protected IFtVerificationPoint VertexServiceVP(TestObject anchor)
	{
		return vp("VertexService", anchor);
	}
	
	

	protected TC02_eSubPurchaseUKHelper()
	{
		setScriptName("scripts_integration.Domestic.eSubscriptionPurchase.eSubscriptionBNWallet.TC02_eSubPurchaseUK");
	}
	
}

