// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.framework.mswallettoolmodel;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>MSWalletToolModel</b><br>
 * Generated     : <b>2014/03/19 11:29:31 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  March 19, 2014
 * @author zsadeque
 */
public abstract class MSWalletToolModelHelper extends RationalTestScript
{
	/**
	 * AccessToken: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Access Token:
	 * 		.classIndex : 1
	 */
	protected GuiTestObject accessToken() 
	{
		return new GuiTestObject(
                        getMappedTestObject("accessToken"));
	}
	/**
	 * AccessToken: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Access Token:
	 * 		.classIndex : 1
	 */
	protected GuiTestObject accessToken(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("accessToken"), anchor, flags);
	}
	
	/**
	 * JComboBox: with default state.
	 *		.itemCount : 18
	 * 		.itemText : {dev01,dev02,dev03,dev04,dev05,dev06,dev07,dev08,qa01}
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Environment:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"));
	}
	/**
	 * JComboBox: with specific test context and state.
	 *		.itemCount : 18
	 * 		.itemText : {dev01,dev02,dev03,dev04,dev05,dev06,dev07,dev08,qa01}
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Environment:
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"), anchor, flags);
	}
	
	/**
	 * JComboBox: with default state.
	 *		.itemCount : 3
	 * 		.itemText : {WEB,WINDEVICE,BINGNEWSSTAND}
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Client Type:
	 * 		.classIndex : 1
	 */
	protected TextSelectGuiSubitemTestObject jComboBox2() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox2"));
	}
	/**
	 * JComboBox: with specific test context and state.
	 *		.itemCount : 3
	 * 		.itemText : {WEB,WINDEVICE,BINGNEWSSTAND}
	 * 		.class : javax.swing.JComboBox
	 * 		.priorLabel : Client Type:
	 * 		.classIndex : 1
	 */
	protected TextSelectGuiSubitemTestObject jComboBox2(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox2"), anchor, flags);
	}
	
	/**
	 * JComboBox: with default state.
	 *		.itemCount : 6
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 2
	 */
	protected TextSelectGuiSubitemTestObject jComboBox3() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox3"));
	}
	/**
	 * JComboBox: with specific test context and state.
	 *		.itemCount : 6
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 2
	 */
	protected TextSelectGuiSubitemTestObject jComboBox3(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox3"), anchor, flags);
	}
	
	/**
	 * JFrame: with default state.
	 *		.captionText : 
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : 
	 */
	protected TopLevelTestObject jFrame() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("jFrame"));
	}
	/**
	 * JFrame: with specific test context and state.
	 *		.captionText : 
	 * 		.class : javax.swing.JFrame
	 * 		accessibleContext.accessibleName : 
	 */
	protected TopLevelTestObject jFrame(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("jFrame"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 2
	 */
	protected TextGuiSubitemTestObject jTextField() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 2
	 */
	protected TextGuiSubitemTestObject jTextField(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 1
	 */
	protected TextGuiSubitemTestObject jTextField2() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField2"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 1
	 */
	protected TextGuiSubitemTestObject jTextField2(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField2"), anchor, flags);
	}
	
	/**
	 * JTextField: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 3
	 */
	protected TextGuiSubitemTestObject jTextField3() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField3"));
	}
	/**
	 * JTextField: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.classIndex : 3
	 */
	protected TextGuiSubitemTestObject jTextField3(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("jTextField3"), anchor, flags);
	}
	
	/**
	 * ManageDefaultPaymentInstrument: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Manage Default Payment Instrument
	 * 		.classIndex : 0
	 */
	protected GuiTestObject manageDefaultPaymentInstrument() 
	{
		return new GuiTestObject(
                        getMappedTestObject("manageDefaultPaymentInstrument"));
	}
	/**
	 * ManageDefaultPaymentInstrument: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Manage Default Payment Instrument
	 * 		.classIndex : 0
	 */
	protected GuiTestObject manageDefaultPaymentInstrument(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("manageDefaultPaymentInstrument"), anchor, flags);
	}
	
	/**
	 * OfflineToken: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Offline Token:
	 * 		.classIndex : 3
	 */
	protected GuiTestObject offlineToken() 
	{
		return new GuiTestObject(
                        getMappedTestObject("offlineToken"));
	}
	/**
	 * OfflineToken: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Offline Token:
	 * 		.classIndex : 3
	 */
	protected GuiTestObject offlineToken(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("offlineToken"), anchor, flags);
	}
	
	/**
	 * RequestCode: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Request Code:
	 * 		.classIndex : 2
	 */
	protected GuiTestObject requestCode() 
	{
		return new GuiTestObject(
                        getMappedTestObject("requestCode"));
	}
	/**
	 * RequestCode: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Request Code:
	 * 		.classIndex : 2
	 */
	protected GuiTestObject requestCode(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("requestCode"), anchor, flags);
	}
	
	/**
	 * textPlain: with default state.
	 *		.class : javax.swing.JTextPane
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject textPlain() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("textPlain"));
	}
	/**
	 * textPlain: with specific test context and state.
	 *		.class : javax.swing.JTextPane
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject textPlain(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("textPlain"), anchor, flags);
	}
	
	/**
	 * textPlain: with default state.
	 *		.class : javax.swing.JTextPane
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject textPlain2() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("textPlain2"));
	}
	/**
	 * textPlain: with specific test context and state.
	 *		.class : javax.swing.JTextPane
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject textPlain2(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("textPlain2"), anchor, flags);
	}
	
	/**
	 * Username: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Username:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject username() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("username"));
	}
	/**
	 * Username: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Username:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject username(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("username"), anchor, flags);
	}
	
	

	protected MSWalletToolModelHelper()
	{
		setScriptName("framework.mswallettoolmodel.MSWalletToolModel");
	}
	
}

