// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.scripts.endtoend;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC01_DeliveryReqAndConf_NoObj</b><br>
 * Generated     : <b>2014/03/03 4:10:50 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  March 03, 2014
 * @author zsadeque
 */
public abstract class TC01_DeliveryReqAndConf_NoObjHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point DeliveryConfirmation object in the SUT.
	 */
	protected IFtVerificationPoint DeliveryConfirmationVP() 
	{
		return vp("DeliveryConfirmation");
	}
	protected IFtVerificationPoint DeliveryConfirmationVP(TestObject anchor)
	{
		return vp("DeliveryConfirmation", anchor);
	}
	
	/**
	 * Locate and return the verification point DeliveryConfirmation_01 object in the SUT.
	 */
	protected IFtVerificationPoint DeliveryConfirmation_01VP() 
	{
		return vp("DeliveryConfirmation_01");
	}
	protected IFtVerificationPoint DeliveryConfirmation_01VP(TestObject anchor)
	{
		return vp("DeliveryConfirmation_01", anchor);
	}
	
	/**
	 * Locate and return the verification point DeliveryConfirmation_01_old object in the SUT.
	 */
	protected IFtVerificationPoint DeliveryConfirmation_01_oldVP() 
	{
		return vp("DeliveryConfirmation_01_old");
	}
	protected IFtVerificationPoint DeliveryConfirmation_01_oldVP(TestObject anchor)
	{
		return vp("DeliveryConfirmation_01_old", anchor);
	}
	
	/**
	 * Locate and return the verification point DeliveryConfirmation_old object in the SUT.
	 */
	protected IFtVerificationPoint DeliveryConfirmation_oldVP() 
	{
		return vp("DeliveryConfirmation_old");
	}
	protected IFtVerificationPoint DeliveryConfirmation_oldVP(TestObject anchor)
	{
		return vp("DeliveryConfirmation_old", anchor);
	}
	
	/**
	 * Locate and return the verification point DeliveryCreated object in the SUT.
	 */
	protected IFtVerificationPoint DeliveryCreatedVP() 
	{
		return vp("DeliveryCreated");
	}
	protected IFtVerificationPoint DeliveryCreatedVP(TestObject anchor)
	{
		return vp("DeliveryCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point DeliveryCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint DeliveryCreated_oldVP() 
	{
		return vp("DeliveryCreated_old");
	}
	protected IFtVerificationPoint DeliveryCreated_oldVP(TestObject anchor)
	{
		return vp("DeliveryCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point gridview object in the SUT.
	 */
	protected IFtVerificationPoint gridviewVP() 
	{
		return vp("gridview");
	}
	protected IFtVerificationPoint gridviewVP(TestObject anchor)
	{
		return vp("gridview", anchor);
	}
	
	/**
	 * Locate and return the verification point OpenOrder object in the SUT.
	 */
	protected IFtVerificationPoint OpenOrderVP() 
	{
		return vp("OpenOrder");
	}
	protected IFtVerificationPoint OpenOrderVP(TestObject anchor)
	{
		return vp("OpenOrder", anchor);
	}
	
	/**
	 * Locate and return the verification point OpenOrder_old object in the SUT.
	 */
	protected IFtVerificationPoint OpenOrder_oldVP() 
	{
		return vp("OpenOrder_old");
	}
	protected IFtVerificationPoint OpenOrder_oldVP(TestObject anchor)
	{
		return vp("OpenOrder_old", anchor);
	}
	
	/**
	 * Locate and return the verification point processedOrder object in the SUT.
	 */
	protected IFtVerificationPoint processedOrderVP() 
	{
		return vp("processedOrder");
	}
	protected IFtVerificationPoint processedOrderVP(TestObject anchor)
	{
		return vp("processedOrder", anchor);
	}
	
	

	protected TC01_DeliveryReqAndConf_NoObjHelper()
	{
		setScriptName("scripts.endtoend.TC01_DeliveryReqAndConf_NoObj");
	}
	
}

