// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sap_scripts.digital;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC02_FreeeBookPurchase</b><br>
 * Generated     : <b>2014/05/07 10:01:48 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  May 07, 2014
 * @author zsadeque
 */
public abstract class TC02_FreeeBookPurchaseHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point Authorized object in the SUT.
	 */
	protected IFtVerificationPoint AuthorizedVP() 
	{
		return vp("Authorized");
	}
	protected IFtVerificationPoint AuthorizedVP(TestObject anchor)
	{
		return vp("Authorized", anchor);
	}
	
	/**
	 * Locate and return the verification point FinalDocFlow_old object in the SUT.
	 */
	protected IFtVerificationPoint FinalDocFlow_oldVP() 
	{
		return vp("FinalDocFlow_old");
	}
	protected IFtVerificationPoint FinalDocFlow_oldVP(TestObject anchor)
	{
		return vp("FinalDocFlow_old", anchor);
	}
	
	/**
	 * Locate and return the verification point IRGotCreated object in the SUT.
	 */
	protected IFtVerificationPoint IRGotCreatedVP() 
	{
		return vp("IRGotCreated");
	}
	protected IFtVerificationPoint IRGotCreatedVP(TestObject anchor)
	{
		return vp("IRGotCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point NetPriceAndTax object in the SUT.
	 */
	protected IFtVerificationPoint NetPriceAndTaxVP() 
	{
		return vp("NetPriceAndTax");
	}
	protected IFtVerificationPoint NetPriceAndTaxVP(TestObject anchor)
	{
		return vp("NetPriceAndTax", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosedVP() 
	{
		return vp("OrderClosed");
	}
	protected IFtVerificationPoint OrderClosedVP(TestObject anchor)
	{
		return vp("OrderClosed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed_old object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosed_oldVP() 
	{
		return vp("OrderClosed_old");
	}
	protected IFtVerificationPoint OrderClosed_oldVP(TestObject anchor)
	{
		return vp("OrderClosed_old", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderProcessed object in the SUT.
	 */
	protected IFtVerificationPoint OrderProcessedVP() 
	{
		return vp("OrderProcessed");
	}
	protected IFtVerificationPoint OrderProcessedVP(TestObject anchor)
	{
		return vp("OrderProcessed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderProcessed_old object in the SUT.
	 */
	protected IFtVerificationPoint OrderProcessed_oldVP() 
	{
		return vp("OrderProcessed_old");
	}
	protected IFtVerificationPoint OrderProcessed_oldVP(TestObject anchor)
	{
		return vp("OrderProcessed_old", anchor);
	}
	
	/**
	 * Locate and return the verification point PartnersTable object in the SUT.
	 */
	protected IFtVerificationPoint PartnersTableVP() 
	{
		return vp("PartnersTable");
	}
	protected IFtVerificationPoint PartnersTableVP(TestObject anchor)
	{
		return vp("PartnersTable", anchor);
	}
	
	/**
	 * Locate and return the verification point SalesData object in the SUT.
	 */
	protected IFtVerificationPoint SalesDataVP() 
	{
		return vp("SalesData");
	}
	protected IFtVerificationPoint SalesDataVP(TestObject anchor)
	{
		return vp("SalesData", anchor);
	}
	
	/**
	 * Locate and return the verification point ZNAPStatus object in the SUT.
	 */
	protected IFtVerificationPoint ZNAPStatusVP() 
	{
		return vp("ZNAPStatus");
	}
	protected IFtVerificationPoint ZNAPStatusVP(TestObject anchor)
	{
		return vp("ZNAPStatus", anchor);
	}
	
	

	protected TC02_FreeeBookPurchaseHelper()
	{
		setScriptName("sap_scripts.digital.TC02_FreeeBookPurchase");
	}
	
}

