// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sap_scripts.digital;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC03_eBookAgencyPurchaseW_GC</b><br>
 * Generated     : <b>2013/12/19 2:19:40 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  December 19, 2013
 * @author zsadeque
 */
public abstract class TC03_eBookAgencyPurchaseW_GCHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point Authorized object in the SUT.
	 */
	protected IFtVerificationPoint AuthorizedVP() 
	{
		return vp("Authorized");
	}
	protected IFtVerificationPoint AuthorizedVP(TestObject anchor)
	{
		return vp("Authorized", anchor);
	}
	
	/**
	 * Locate and return the verification point FinalDocFlow object in the SUT.
	 */
	protected IFtVerificationPoint FinalDocFlowVP() 
	{
		return vp("FinalDocFlow");
	}
	protected IFtVerificationPoint FinalDocFlowVP(TestObject anchor)
	{
		return vp("FinalDocFlow", anchor);
	}
	
	/**
	 * Locate and return the verification point FinalDocFlow_old object in the SUT.
	 */
	protected IFtVerificationPoint FinalDocFlow_oldVP() 
	{
		return vp("FinalDocFlow_old");
	}
	protected IFtVerificationPoint FinalDocFlow_oldVP(TestObject anchor)
	{
		return vp("FinalDocFlow_old", anchor);
	}
	
	/**
	 * Locate and return the verification point IRGotCreated object in the SUT.
	 */
	protected IFtVerificationPoint IRGotCreatedVP() 
	{
		return vp("IRGotCreated");
	}
	protected IFtVerificationPoint IRGotCreatedVP(TestObject anchor)
	{
		return vp("IRGotCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point NetPriceAndTax object in the SUT.
	 */
	protected IFtVerificationPoint NetPriceAndTaxVP() 
	{
		return vp("NetPriceAndTax");
	}
	protected IFtVerificationPoint NetPriceAndTaxVP(TestObject anchor)
	{
		return vp("NetPriceAndTax", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosedVP() 
	{
		return vp("OrderClosed");
	}
	protected IFtVerificationPoint OrderClosedVP(TestObject anchor)
	{
		return vp("OrderClosed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed_old object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosed_oldVP() 
	{
		return vp("OrderClosed_old");
	}
	protected IFtVerificationPoint OrderClosed_oldVP(TestObject anchor)
	{
		return vp("OrderClosed_old", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderProcessed object in the SUT.
	 */
	protected IFtVerificationPoint OrderProcessedVP() 
	{
		return vp("OrderProcessed");
	}
	protected IFtVerificationPoint OrderProcessedVP(TestObject anchor)
	{
		return vp("OrderProcessed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderProcessed_old object in the SUT.
	 */
	protected IFtVerificationPoint OrderProcessed_oldVP() 
	{
		return vp("OrderProcessed_old");
	}
	protected IFtVerificationPoint OrderProcessed_oldVP(TestObject anchor)
	{
		return vp("OrderProcessed_old", anchor);
	}
	
	/**
	 * Locate and return the verification point PartnersTable object in the SUT.
	 */
	protected IFtVerificationPoint PartnersTableVP() 
	{
		return vp("PartnersTable");
	}
	protected IFtVerificationPoint PartnersTableVP(TestObject anchor)
	{
		return vp("PartnersTable", anchor);
	}
	
	/**
	 * Locate and return the verification point SalesData object in the SUT.
	 */
	protected IFtVerificationPoint SalesDataVP() 
	{
		return vp("SalesData");
	}
	protected IFtVerificationPoint SalesDataVP(TestObject anchor)
	{
		return vp("SalesData", anchor);
	}
	
	/**
	 * Locate and return the verification point ZEAMStatus object in the SUT.
	 */
	protected IFtVerificationPoint ZEAMStatusVP() 
	{
		return vp("ZEAMStatus");
	}
	protected IFtVerificationPoint ZEAMStatusVP(TestObject anchor)
	{
		return vp("ZEAMStatus", anchor);
	}
	
	

	protected TC03_eBookAgencyPurchaseW_GCHelper()
	{
		setScriptName("sap_scripts.digital.TC03_eBookAgencyPurchaseW_GC");
	}
	
}

