// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.scripts.sap;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC02_AccessoryPurchase</b><br>
 * Generated     : <b>2013/07/01 2:54:55 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  July 01, 2013
 * @author zsadeque
 */
public abstract class TC02_AccessoryPurchaseHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point OrderDetails object in the SUT.
	 */
	protected IFtVerificationPoint OrderDetailsVP() 
	{
		return vp("OrderDetails");
	}
	protected IFtVerificationPoint OrderDetailsVP(TestObject anchor)
	{
		return vp("OrderDetails", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderStatus object in the SUT.
	 */
	protected IFtVerificationPoint OrderStatusVP() 
	{
		return vp("OrderStatus");
	}
	protected IFtVerificationPoint OrderStatusVP(TestObject anchor)
	{
		return vp("OrderStatus", anchor);
	}
	
	

	protected TC02_AccessoryPurchaseHelper()
	{
		setScriptName("scripts.sap.TC02_AccessoryPurchase");
	}
	
}

