// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.tempscripts;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC01_PhysicalPurchase</b><br>
 * Generated     : <b>2013/09/05 4:42:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  September 05, 2013
 * @author zsadeque
 */
public abstract class TC01_PhysicalPurchaseHelper extends framework.AtlasScriptbase
{
	/**
	 * KOMFKVBELN: with default state.
	 *		Name : KOMFK-VBELN
	 * 		Id : /ctxtKOMFK-VBELN[0,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Document
	 */
	protected SAPGuiTextTestObject text_komfkvbeln() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_komfkvbeln"));
	}
	/**
	 * KOMFKVBELN: with specific test context and state.
	 *		Name : KOMFK-VBELN
	 * 		Id : /ctxtKOMFK-VBELN[0,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Document
	 */
	protected SAPGuiTextTestObject text_komfkvbeln(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_komfkvbeln"), anchor, flags);
	}
	
	/**
	 * CreateBillingDocument: with default state.
	 *		Name : wnd[0]
	 * 		Text : Create Billing Document
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_createBillingDocument() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_createBillingDocument"));
	}
	/**
	 * CreateBillingDocument: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : Create Billing Document
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_createBillingDocument(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_createBillingDocument"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point CC_Status_AB object in the SUT.
	 */
	protected IFtVerificationPoint CC_Status_ABVP() 
	{
		return vp("CC_Status_AB");
	}
	protected IFtVerificationPoint CC_Status_ABVP(TestObject anchor)
	{
		return vp("CC_Status_AB", anchor);
	}
	
	/**
	 * Locate and return the verification point CC_Status_LA_AB object in the SUT.
	 */
	protected IFtVerificationPoint CC_Status_LA_ABVP() 
	{
		return vp("CC_Status_LA_AB");
	}
	protected IFtVerificationPoint CC_Status_LA_ABVP(TestObject anchor)
	{
		return vp("CC_Status_LA_AB", anchor);
	}
	
	/**
	 * Locate and return the verification point EmptyConfirmTable object in the SUT.
	 */
	protected IFtVerificationPoint EmptyConfirmTableVP() 
	{
		return vp("EmptyConfirmTable");
	}
	protected IFtVerificationPoint EmptyConfirmTableVP(TestObject anchor)
	{
		return vp("EmptyConfirmTable", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbdDeliveryCreated object in the SUT.
	 */
	protected IFtVerificationPoint OutbdDeliveryCreatedVP() 
	{
		return vp("OutbdDeliveryCreated");
	}
	protected IFtVerificationPoint OutbdDeliveryCreatedVP(TestObject anchor)
	{
		return vp("OutbdDeliveryCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreated object in the SUT.
	 */
	protected IFtVerificationPoint POCreatedVP() 
	{
		return vp("POCreated");
	}
	protected IFtVerificationPoint POCreatedVP(TestObject anchor)
	{
		return vp("POCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point Status_53 object in the SUT.
	 */
	protected IFtVerificationPoint Status_53VP() 
	{
		return vp("Status_53");
	}
	protected IFtVerificationPoint Status_53VP(TestObject anchor)
	{
		return vp("Status_53", anchor);
	}
	
	

	protected TC01_PhysicalPurchaseHelper()
	{
		setScriptName("tempscripts.TC01_PhysicalPurchase");
	}
	
}

