// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.scripts.gxs_inbound.positive;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC11_PurchaseOrderAcknowledgementExternal</b><br>
 * Generated     : <b>2013/06/11 2:07:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  June 11, 2013
 * @author zsadeque
 */
public abstract class TC11_PurchaseOrderAcknowledgementExternalHelper extends framework.AtlasScriptbase
{
	

	protected TC11_PurchaseOrderAcknowledgementExternalHelper()
	{
		setScriptName("scripts.gxs_inbound.positive.TC11_PurchaseOrderAcknowledgementExternal");
	}
	
}

