// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.scripts.gxs_inbound.positive;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC13_EndToEnd</b><br>
 * Generated     : <b>2013/12/20 12:14:57 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  December 20, 2013
 * @author zsadeque
 */
public abstract class TC13_EndToEndHelper extends framework.AtlasScriptbase
{
	/**
	 * VBAKFAKSK: with default state.
	 *		Name : VBAK-FAKSK
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/cmbVBAK-FAKSK
	 * 		.class : GuiComboBox
	 * 		.priorLabel : Billing block
	 */
	protected SAPGuiComboBoxTestObject comboBox_vbakfaksk() 
	{
		return new SAPGuiComboBoxTestObject(
                        getMappedTestObject("comboBox_vbakfaksk"));
	}
	/**
	 * VBAKFAKSK: with specific test context and state.
	 *		Name : VBAK-FAKSK
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/cmbVBAK-FAKSK
	 * 		.class : GuiComboBox
	 * 		.priorLabel : Billing block
	 */
	protected SAPGuiComboBoxTestObject comboBox_vbakfaksk(TestObject anchor, long flags) 
	{
		return new SAPGuiComboBoxTestObject(
                        getMappedTestObject("comboBox_vbakfaksk"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point AB_LA_Created object in the SUT.
	 */
	protected IFtVerificationPoint AB_LA_CreatedVP() 
	{
		return vp("AB_LA_Created");
	}
	protected IFtVerificationPoint AB_LA_CreatedVP(TestObject anchor)
	{
		return vp("AB_LA_Created", anchor);
	}
	
	/**
	 * Locate and return the verification point AccountDocCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint AccountDocCreated_oldVP() 
	{
		return vp("AccountDocCreated_old");
	}
	protected IFtVerificationPoint AccountDocCreated_oldVP(TestObject anchor)
	{
		return vp("AccountDocCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point ApprovedPO object in the SUT.
	 */
	protected IFtVerificationPoint ApprovedPOVP() 
	{
		return vp("ApprovedPO");
	}
	protected IFtVerificationPoint ApprovedPOVP(TestObject anchor)
	{
		return vp("ApprovedPO", anchor);
	}
	
	/**
	 * Locate and return the verification point BlankConf object in the SUT.
	 */
	protected IFtVerificationPoint BlankConfVP() 
	{
		return vp("BlankConf");
	}
	protected IFtVerificationPoint BlankConfVP(TestObject anchor)
	{
		return vp("BlankConf", anchor);
	}
	
	/**
	 * Locate and return the verification point ConfOfService_old object in the SUT.
	 */
	protected IFtVerificationPoint ConfOfService_oldVP() 
	{
		return vp("ConfOfService_old");
	}
	protected IFtVerificationPoint ConfOfService_oldVP(TestObject anchor)
	{
		return vp("ConfOfService_old", anchor);
	}
	
	/**
	 * Locate and return the verification point ConfOfService_old2 object in the SUT.
	 */
	protected IFtVerificationPoint ConfOfService_old2VP() 
	{
		return vp("ConfOfService_old2");
	}
	protected IFtVerificationPoint ConfOfService_old2VP(TestObject anchor)
	{
		return vp("ConfOfService_old2", anchor);
	}
	
	/**
	 * Locate and return the verification point DeviceDelNAccDocCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint DeviceDelNAccDocCreated_oldVP() 
	{
		return vp("DeviceDelNAccDocCreated_old");
	}
	protected IFtVerificationPoint DeviceDelNAccDocCreated_oldVP(TestObject anchor)
	{
		return vp("DeviceDelNAccDocCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point DeviceDelNAccDocCreated_old21 object in the SUT.
	 */
	protected IFtVerificationPoint DeviceDelNAccDocCreated_old21VP() 
	{
		return vp("DeviceDelNAccDocCreated_old21");
	}
	protected IFtVerificationPoint DeviceDelNAccDocCreated_old21VP(TestObject anchor)
	{
		return vp("DeviceDelNAccDocCreated_old21", anchor);
	}
	
	/**
	 * Locate and return the verification point deviceOrderWhSaleSaved object in the SUT.
	 */
	protected IFtVerificationPoint deviceOrderWhSaleSavedVP() 
	{
		return vp("deviceOrderWhSaleSaved");
	}
	protected IFtVerificationPoint deviceOrderWhSaleSavedVP(TestObject anchor)
	{
		return vp("deviceOrderWhSaleSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point deviceOrderWhSaleSaved_old object in the SUT.
	 */
	protected IFtVerificationPoint deviceOrderWhSaleSaved_oldVP() 
	{
		return vp("deviceOrderWhSaleSaved_old");
	}
	protected IFtVerificationPoint deviceOrderWhSaleSaved_oldVP(TestObject anchor)
	{
		return vp("deviceOrderWhSaleSaved_old", anchor);
	}
	
	/**
	 * Locate and return the verification point DocumentDetails object in the SUT.
	 */
	protected IFtVerificationPoint DocumentDetailsVP() 
	{
		return vp("DocumentDetails");
	}
	protected IFtVerificationPoint DocumentDetailsVP(TestObject anchor)
	{
		return vp("DocumentDetails", anchor);
	}
	
	/**
	 * Locate and return the verification point GreenStatus object in the SUT.
	 */
	protected IFtVerificationPoint GreenStatusVP() 
	{
		return vp("GreenStatus");
	}
	protected IFtVerificationPoint GreenStatusVP(TestObject anchor)
	{
		return vp("GreenStatus", anchor);
	}
	
	/**
	 * Locate and return the verification point InvoiceDocumentSaved object in the SUT.
	 */
	protected IFtVerificationPoint InvoiceDocumentSavedVP() 
	{
		return vp("InvoiceDocumentSaved");
	}
	protected IFtVerificationPoint InvoiceDocumentSavedVP(TestObject anchor)
	{
		return vp("InvoiceDocumentSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point IRGenerated object in the SUT.
	 */
	protected IFtVerificationPoint IRGeneratedVP() 
	{
		return vp("IRGenerated");
	}
	protected IFtVerificationPoint IRGeneratedVP(TestObject anchor)
	{
		return vp("IRGenerated", anchor);
	}
	
	/**
	 * Locate and return the verification point New03Status object in the SUT.
	 */
	protected IFtVerificationPoint New03StatusVP() 
	{
		return vp("New03Status");
	}
	protected IFtVerificationPoint New03StatusVP(TestObject anchor)
	{
		return vp("New03Status", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderDetails object in the SUT.
	 */
	protected IFtVerificationPoint OrderDetailsVP() 
	{
		return vp("OrderDetails");
	}
	protected IFtVerificationPoint OrderDetailsVP(TestObject anchor)
	{
		return vp("OrderDetails", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbDelOpenStatus_old object in the SUT.
	 */
	protected IFtVerificationPoint OutbDelOpenStatus_oldVP() 
	{
		return vp("OutbDelOpenStatus_old");
	}
	protected IFtVerificationPoint OutbDelOpenStatus_oldVP(TestObject anchor)
	{
		return vp("OutbDelOpenStatus_old", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbDelOpenStatus_old2 object in the SUT.
	 */
	protected IFtVerificationPoint OutbDelOpenStatus_old2VP() 
	{
		return vp("OutbDelOpenStatus_old2");
	}
	protected IFtVerificationPoint OutbDelOpenStatus_old2VP(TestObject anchor)
	{
		return vp("OutbDelOpenStatus_old2", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbDelSaved object in the SUT.
	 */
	protected IFtVerificationPoint OutbDelSavedVP() 
	{
		return vp("OutbDelSaved");
	}
	protected IFtVerificationPoint OutbDelSavedVP(TestObject anchor)
	{
		return vp("OutbDelSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbDelSaved_old object in the SUT.
	 */
	protected IFtVerificationPoint OutbDelSaved_oldVP() 
	{
		return vp("OutbDelSaved_old");
	}
	protected IFtVerificationPoint OutbDelSaved_oldVP(TestObject anchor)
	{
		return vp("OutbDelSaved_old", anchor);
	}
	
	/**
	 * Locate and return the verification point POACK object in the SUT.
	 */
	protected IFtVerificationPoint POACKVP() 
	{
		return vp("POACK");
	}
	protected IFtVerificationPoint POACKVP(TestObject anchor)
	{
		return vp("POACK", anchor);
	}
	
	/**
	 * Locate and return the verification point PODetails object in the SUT.
	 */
	protected IFtVerificationPoint PODetailsVP() 
	{
		return vp("PODetails");
	}
	protected IFtVerificationPoint PODetailsVP(TestObject anchor)
	{
		return vp("PODetails", anchor);
	}
	
	/**
	 * Locate and return the verification point PurchaseChanged object in the SUT.
	 */
	protected IFtVerificationPoint PurchaseChangedVP() 
	{
		return vp("PurchaseChanged");
	}
	protected IFtVerificationPoint PurchaseChangedVP(TestObject anchor)
	{
		return vp("PurchaseChanged", anchor);
	}
	
	/**
	 * Locate and return the verification point Released object in the SUT.
	 */
	protected IFtVerificationPoint ReleasedVP() 
	{
		return vp("Released");
	}
	protected IFtVerificationPoint ReleasedVP(TestObject anchor)
	{
		return vp("Released", anchor);
	}
	
	/**
	 * Locate and return the verification point RequisitionCreated object in the SUT.
	 */
	protected IFtVerificationPoint RequisitionCreatedVP() 
	{
		return vp("RequisitionCreated");
	}
	protected IFtVerificationPoint RequisitionCreatedVP(TestObject anchor)
	{
		return vp("RequisitionCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point ReviewPlanner object in the SUT.
	 */
	protected IFtVerificationPoint ReviewPlannerVP() 
	{
		return vp("ReviewPlanner");
	}
	protected IFtVerificationPoint ReviewPlannerVP(TestObject anchor)
	{
		return vp("ReviewPlanner", anchor);
	}
	
	/**
	 * Locate and return the verification point SourceOverviewTable object in the SUT.
	 */
	protected IFtVerificationPoint SourceOverviewTableVP() 
	{
		return vp("SourceOverviewTable");
	}
	protected IFtVerificationPoint SourceOverviewTableVP(TestObject anchor)
	{
		return vp("SourceOverviewTable", anchor);
	}
	
	/**
	 * Locate and return the verification point Updatedto3PL object in the SUT.
	 */
	protected IFtVerificationPoint Updatedto3PLVP() 
	{
		return vp("Updatedto3PL");
	}
	protected IFtVerificationPoint Updatedto3PLVP(TestObject anchor)
	{
		return vp("Updatedto3PL", anchor);
	}
	
	/**
	 * Locate and return the verification point VendorAssigned object in the SUT.
	 */
	protected IFtVerificationPoint VendorAssignedVP() 
	{
		return vp("VendorAssigned");
	}
	protected IFtVerificationPoint VendorAssignedVP(TestObject anchor)
	{
		return vp("VendorAssigned", anchor);
	}
	
	

	protected TC13_EndToEndHelper()
	{
		setScriptName("scripts.gxs_inbound.positive.TC13_EndToEnd");
	}
	
}

