// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.framework.pfstoolsmodel;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PFSApplicationModel</b><br>
 * Generated     : <b>2013/09/12 2:58:04 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  September 12, 2013
 * @author zsadeque
 */
public abstract class PFSApplicationModelHelper extends RationalTestScript
{
	/**
	 * PFSMessageTestTool: with default state.
	 *		Name : frmClient
	 * 		Text : PFS Message Test Tool
	 * 		TabIndex : 0
	 * 		.class : PFSTool.frmClient
	 * 		.processName : PFSTool.exe
	 * 		.classIndex : 0
	 */
	protected TopLevelSubitemTestObject pfsMessageTestToolwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("pfsMessageTestToolwindow"));
	}
	/**
	 * PFSMessageTestTool: with specific test context and state.
	 *		Name : frmClient
	 * 		Text : PFS Message Test Tool
	 * 		TabIndex : 0
	 * 		.class : PFSTool.frmClient
	 * 		.processName : PFSTool.exe
	 * 		.classIndex : 0
	 */
	protected TopLevelSubitemTestObject pfsMessageTestToolwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("pfsMessageTestToolwindow"), anchor, flags);
	}
	
	

	protected PFSApplicationModelHelper()
	{
		setScriptName("framework.pfstoolsmodel.PFSApplicationModel");
	}
	
}

