// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.scripts.outboudsapactions.withoutingestion.bnwallet;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC11_ROUPDATEPAYMENTMETHOD</b><br>
 * Generated     : <b>2014/08/07 4:43:44 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  August 07, 2014
 * @author zsadeque
 */
public abstract class TC11_ROUPDATEPAYMENTMETHODHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point BNIncDB_Customer_Closed object in the SUT.
	 */
	protected IFtVerificationPoint BNIncDB_Customer_ClosedVP() 
	{
		return vp("BNIncDB_Customer_Closed");
	}
	protected IFtVerificationPoint BNIncDB_Customer_ClosedVP(TestObject anchor)
	{
		return vp("BNIncDB_Customer_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point BNIncDB_Customer_Open object in the SUT.
	 */
	protected IFtVerificationPoint BNIncDB_Customer_OpenVP() 
	{
		return vp("BNIncDB_Customer_Open");
	}
	protected IFtVerificationPoint BNIncDB_Customer_OpenVP(TestObject anchor)
	{
		return vp("BNIncDB_Customer_Open", anchor);
	}
	
	/**
	 * Locate and return the verification point BNIncDB_OrderHeader_Closed object in the SUT.
	 */
	protected IFtVerificationPoint BNIncDB_OrderHeader_ClosedVP() 
	{
		return vp("BNIncDB_OrderHeader_Closed");
	}
	protected IFtVerificationPoint BNIncDB_OrderHeader_ClosedVP(TestObject anchor)
	{
		return vp("BNIncDB_OrderHeader_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point BNIncDB_OrderHeader_Open object in the SUT.
	 */
	protected IFtVerificationPoint BNIncDB_OrderHeader_OpenVP() 
	{
		return vp("BNIncDB_OrderHeader_Open");
	}
	protected IFtVerificationPoint BNIncDB_OrderHeader_OpenVP(TestObject anchor)
	{
		return vp("BNIncDB_OrderHeader_Open", anchor);
	}
	
	/**
	 * Locate and return the verification point DWDB_Customer_Closed object in the SUT.
	 */
	protected IFtVerificationPoint DWDB_Customer_ClosedVP() 
	{
		return vp("DWDB_Customer_Closed");
	}
	protected IFtVerificationPoint DWDB_Customer_ClosedVP(TestObject anchor)
	{
		return vp("DWDB_Customer_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point DWDB_Customer_Open object in the SUT.
	 */
	protected IFtVerificationPoint DWDB_Customer_OpenVP() 
	{
		return vp("DWDB_Customer_Open");
	}
	protected IFtVerificationPoint DWDB_Customer_OpenVP(TestObject anchor)
	{
		return vp("DWDB_Customer_Open", anchor);
	}
	
	/**
	 * Locate and return the verification point DWDB_OrderCCNumber_Closed object in the SUT.
	 */
	protected IFtVerificationPoint DWDB_OrderCCNumber_ClosedVP() 
	{
		return vp("DWDB_OrderCCNumber_Closed");
	}
	protected IFtVerificationPoint DWDB_OrderCCNumber_ClosedVP(TestObject anchor)
	{
		return vp("DWDB_OrderCCNumber_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point DWDB_OrderCCNumber_Open object in the SUT.
	 */
	protected IFtVerificationPoint DWDB_OrderCCNumber_OpenVP() 
	{
		return vp("DWDB_OrderCCNumber_Open");
	}
	protected IFtVerificationPoint DWDB_OrderCCNumber_OpenVP(TestObject anchor)
	{
		return vp("DWDB_OrderCCNumber_Open", anchor);
	}
	
	/**
	 * Locate and return the verification point DWDB_OrderHeader_Closed object in the SUT.
	 */
	protected IFtVerificationPoint DWDB_OrderHeader_ClosedVP() 
	{
		return vp("DWDB_OrderHeader_Closed");
	}
	protected IFtVerificationPoint DWDB_OrderHeader_ClosedVP(TestObject anchor)
	{
		return vp("DWDB_OrderHeader_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point DWDB_OrderHeader_Open object in the SUT.
	 */
	protected IFtVerificationPoint DWDB_OrderHeader_OpenVP() 
	{
		return vp("DWDB_OrderHeader_Open");
	}
	protected IFtVerificationPoint DWDB_OrderHeader_OpenVP(TestObject anchor)
	{
		return vp("DWDB_OrderHeader_Open", anchor);
	}
	
	/**
	 * Locate and return the verification point iDocList object in the SUT.
	 */
	protected IFtVerificationPoint iDocListVP() 
	{
		return vp("iDocList");
	}
	protected IFtVerificationPoint iDocListVP(TestObject anchor)
	{
		return vp("iDocList", anchor);
	}
	
	/**
	 * Locate and return the verification point IPStatus object in the SUT.
	 */
	protected IFtVerificationPoint IPStatusVP() 
	{
		return vp("IPStatus");
	}
	protected IFtVerificationPoint IPStatusVP(TestObject anchor)
	{
		return vp("IPStatus", anchor);
	}
	
	/**
	 * Locate and return the verification point NoError object in the SUT.
	 */
	protected IFtVerificationPoint NoErrorVP() 
	{
		return vp("NoError");
	}
	protected IFtVerificationPoint NoErrorVP(TestObject anchor)
	{
		return vp("NoError", anchor);
	}
	
	/**
	 * Locate and return the verification point OSDB_OrderHeader_Closed object in the SUT.
	 */
	protected IFtVerificationPoint OSDB_OrderHeader_ClosedVP() 
	{
		return vp("OSDB_OrderHeader_Closed");
	}
	protected IFtVerificationPoint OSDB_OrderHeader_ClosedVP(TestObject anchor)
	{
		return vp("OSDB_OrderHeader_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point OSDB_OrderHeader_Open object in the SUT.
	 */
	protected IFtVerificationPoint OSDB_OrderHeader_OpenVP() 
	{
		return vp("OSDB_OrderHeader_Open");
	}
	protected IFtVerificationPoint OSDB_OrderHeader_OpenVP(TestObject anchor)
	{
		return vp("OSDB_OrderHeader_Open", anchor);
	}
	
	/**
	 * Locate and return the verification point paymmentCard object in the SUT.
	 */
	protected IFtVerificationPoint paymmentCardVP() 
	{
		return vp("paymmentCard");
	}
	protected IFtVerificationPoint paymmentCardVP(TestObject anchor)
	{
		return vp("paymmentCard", anchor);
	}
	
	/**
	 * Locate and return the verification point SalesRankDB_OrderDetail_Closed object in the SUT.
	 */
	protected IFtVerificationPoint SalesRankDB_OrderDetail_ClosedVP() 
	{
		return vp("SalesRankDB_OrderDetail_Closed");
	}
	protected IFtVerificationPoint SalesRankDB_OrderDetail_ClosedVP(TestObject anchor)
	{
		return vp("SalesRankDB_OrderDetail_Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point SalesRankDB_OrderDetail_Open object in the SUT.
	 */
	protected IFtVerificationPoint SalesRankDB_OrderDetail_OpenVP() 
	{
		return vp("SalesRankDB_OrderDetail_Open");
	}
	protected IFtVerificationPoint SalesRankDB_OrderDetail_OpenVP(TestObject anchor)
	{
		return vp("SalesRankDB_OrderDetail_Open", anchor);
	}
	
	

	protected TC11_ROUPDATEPAYMENTMETHODHelper()
	{
		setScriptName("scripts.outboudsapactions.withoutingestion.bnwallet.TC11_ROUPDATEPAYMENTMETHOD");
	}
	
}

