// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.framework.sapmodel;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SAPLogon720PageModel</b><br>
 * Generated     : <b>2014/03/03 4:05:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  March 03, 2014
 * @author zsadeque
 */
public abstract class SAPLogon720PageModelHelper extends RationalTestScript
{
	/**
	 * SAPLogon730: with default state.
	 *		.text : SAP Logon 730
	 * 		.class : #32770
	 * 		.processName : saplogon.exe
	 * 		.name : SAP Logon 730
	 */
	protected TopLevelSubitemTestObject sapLogon730window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sapLogon730window"));
	}
	/**
	 * SAPLogon730: with specific test context and state.
	 *		.text : SAP Logon 730
	 * 		.class : #32770
	 * 		.processName : saplogon.exe
	 * 		.name : SAP Logon 730
	 */
	protected TopLevelSubitemTestObject sapLogon730window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sapLogon730window"), anchor, flags);
	}
	
	/**
	 * SysListView32: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table2() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table2"));
	}
	/**
	 * SysListView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table2(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table2"), anchor, flags);
	}
	
	

	protected SAPLogon720PageModelHelper()
	{
		setScriptName("framework.sapmodel.SAPLogon720PageModel");
	}
	
}

