// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.framework.sapmodel;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SAPRQ1UserLoginDialogModel</b><br>
 * Generated     : <b>2013/05/03 3:14:53 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  May 03, 2013
 * @author fahmed1
 */
public abstract class SAPRQ1UserLoginDialogModelHelper extends RationalTestScript
{
	/**
	 * RSYSTBCODE: with default state.
	 *		Name : RSYST-BCODE
	 * 		Id : /pwdRSYST-BCODE
	 * 		.class : GuiPasswordField
	 * 		.priorLabel : Password
	 */
	protected SAPGuiTextTestObject text_rsystbcode() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbcode"));
	}
	/**
	 * RSYSTBCODE: with specific test context and state.
	 *		Name : RSYST-BCODE
	 * 		Id : /pwdRSYST-BCODE
	 * 		.class : GuiPasswordField
	 * 		.priorLabel : Password
	 */
	protected SAPGuiTextTestObject text_rsystbcode(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbcode"), anchor, flags);
	}
	
	/**
	 * RSYSTBNAME: with default state.
	 *		Name : RSYST-BNAME
	 * 		Id : /txtRSYST-BNAME
	 * 		.class : GuiTextField
	 * 		.priorLabel : User
	 */
	protected SAPGuiTextTestObject text_rsystbname() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbname"));
	}
	/**
	 * RSYSTBNAME: with specific test context and state.
	 *		Name : RSYST-BNAME
	 * 		Id : /txtRSYST-BNAME
	 * 		.class : GuiTextField
	 * 		.priorLabel : User
	 */
	protected SAPGuiTextTestObject text_rsystbname(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbname"), anchor, flags);
	}
	
	/**
	 * SAP: with default state.
	 *		Name : wnd[0]
	 * 		Text : SAP
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_sap() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_sap"));
	}
	/**
	 * SAP: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : SAP
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_sap(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_sap"), anchor, flags);
	}
	
	

	protected SAPRQ1UserLoginDialogModelHelper()
	{
		setScriptName("framework.sapmodel.SAPRQ1UserLoginDialogModel");
	}
	
}

