// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sap_scripts.physical;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC01_BookPurchaseWValidCC</b><br>
 * Generated     : <b>2013/12/18 3:46:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  December 18, 2013
 * @author zsadeque
 */
public abstract class TC01_BookPurchaseWValidCCHelper extends framework.AtlasScriptbase
{
	/**
	 * KOMFKVBELN: with default state.
	 *		Name : KOMFK-VBELN
	 * 		Id : /ctxtKOMFK-VBELN[0,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Document
	 */
	protected SAPGuiTextTestObject text_komfkvbeln() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_komfkvbeln"));
	}
	/**
	 * KOMFKVBELN: with specific test context and state.
	 *		Name : KOMFK-VBELN
	 * 		Id : /ctxtKOMFK-VBELN[0,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Document
	 */
	protected SAPGuiTextTestObject text_komfkvbeln(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_komfkvbeln"), anchor, flags);
	}
	
	/**
	 * SAPTableTreeControl1: with default state.
	 *		Name : shell[1]
	 * 		Id : /shell/shellcont[1]/shell[1]
	 * 		.class : GuiShell.Tree
	 */
	protected SAPGuiCtrlTreeTestObject tree_sapTableTreeControl1() 
	{
		return new SAPGuiCtrlTreeTestObject(
                        getMappedTestObject("tree_sapTableTreeControl1"));
	}
	/**
	 * SAPTableTreeControl1: with specific test context and state.
	 *		Name : shell[1]
	 * 		Id : /shell/shellcont[1]/shell[1]
	 * 		.class : GuiShell.Tree
	 */
	protected SAPGuiCtrlTreeTestObject tree_sapTableTreeControl1(TestObject anchor, long flags) 
	{
		return new SAPGuiCtrlTreeTestObject(
                        getMappedTestObject("tree_sapTableTreeControl1"), anchor, flags);
	}
	
	/**
	 * CreateBillingDocument: with default state.
	 *		Name : wnd[0]
	 * 		Text : Create Billing Document
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_createBillingDocument() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_createBillingDocument"));
	}
	/**
	 * CreateBillingDocument: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : Create Billing Document
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_createBillingDocument(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_createBillingDocument"), anchor, flags);
	}
	
	/**
	 * DocumentFlow: with default state.
	 *		Name : wnd[0]
	 * 		.connectionNumber : 0
	 * 		Text : Document Flow
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_documentFlow() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_documentFlow"));
	}
	/**
	 * DocumentFlow: with specific test context and state.
	 *		Name : wnd[0]
	 * 		.connectionNumber : 0
	 * 		Text : Document Flow
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_documentFlow(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_documentFlow"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point BilledAndAccountingDocCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint BilledAndAccountingDocCreated_oldVP() 
	{
		return vp("BilledAndAccountingDocCreated_old");
	}
	protected IFtVerificationPoint BilledAndAccountingDocCreated_oldVP(TestObject anchor)
	{
		return vp("BilledAndAccountingDocCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point CC_Status_AB object in the SUT.
	 */
	protected IFtVerificationPoint CC_Status_ABVP() 
	{
		return vp("CC_Status_AB");
	}
	protected IFtVerificationPoint CC_Status_ABVP(TestObject anchor)
	{
		return vp("CC_Status_AB", anchor);
	}
	
	/**
	 * Locate and return the verification point CC_Status_LA_AB object in the SUT.
	 */
	protected IFtVerificationPoint CC_Status_LA_ABVP() 
	{
		return vp("CC_Status_LA_AB");
	}
	protected IFtVerificationPoint CC_Status_LA_ABVP(TestObject anchor)
	{
		return vp("CC_Status_LA_AB", anchor);
	}
	
	/**
	 * Locate and return the verification point DocumentSaved object in the SUT.
	 */
	protected IFtVerificationPoint DocumentSavedVP() 
	{
		return vp("DocumentSaved");
	}
	protected IFtVerificationPoint DocumentSavedVP(TestObject anchor)
	{
		return vp("DocumentSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point empty object in the SUT.
	 */
	protected IFtVerificationPoint emptyVP() 
	{
		return vp("empty");
	}
	protected IFtVerificationPoint emptyVP(TestObject anchor)
	{
		return vp("empty", anchor);
	}
	
	/**
	 * Locate and return the verification point EmptyConfirmTable object in the SUT.
	 */
	protected IFtVerificationPoint EmptyConfirmTableVP() 
	{
		return vp("EmptyConfirmTable");
	}
	protected IFtVerificationPoint EmptyConfirmTableVP(TestObject anchor)
	{
		return vp("EmptyConfirmTable", anchor);
	}
	
	/**
	 * Locate and return the verification point FinalDocFlow_old object in the SUT.
	 */
	protected IFtVerificationPoint FinalDocFlow_oldVP() 
	{
		return vp("FinalDocFlow_old");
	}
	protected IFtVerificationPoint FinalDocFlow_oldVP(TestObject anchor)
	{
		return vp("FinalDocFlow_old", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosedVP() 
	{
		return vp("OrderClosed");
	}
	protected IFtVerificationPoint OrderClosedVP(TestObject anchor)
	{
		return vp("OrderClosed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderEmails object in the SUT.
	 */
	protected IFtVerificationPoint OrderEmailsVP() 
	{
		return vp("OrderEmails");
	}
	protected IFtVerificationPoint OrderEmailsVP(TestObject anchor)
	{
		return vp("OrderEmails", anchor);
	}
	
	/**
	 * Locate and return the verification point orderTable object in the SUT.
	 */
	protected IFtVerificationPoint orderTableVP() 
	{
		return vp("orderTable");
	}
	protected IFtVerificationPoint orderTableVP(TestObject anchor)
	{
		return vp("orderTable", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbdDeliveryCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint OutbdDeliveryCreated_oldVP() 
	{
		return vp("OutbdDeliveryCreated_old");
	}
	protected IFtVerificationPoint OutbdDeliveryCreated_oldVP(TestObject anchor)
	{
		return vp("OutbdDeliveryCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbdDeliveryCreated_old2 object in the SUT.
	 */
	protected IFtVerificationPoint OutbdDeliveryCreated_old2VP() 
	{
		return vp("OutbdDeliveryCreated_old2");
	}
	protected IFtVerificationPoint OutbdDeliveryCreated_old2VP(TestObject anchor)
	{
		return vp("OutbdDeliveryCreated_old2", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint POCreated_oldVP() 
	{
		return vp("POCreated_old");
	}
	protected IFtVerificationPoint POCreated_oldVP(TestObject anchor)
	{
		return vp("POCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreated_old2 object in the SUT.
	 */
	protected IFtVerificationPoint POCreated_old2VP() 
	{
		return vp("POCreated_old2");
	}
	protected IFtVerificationPoint POCreated_old2VP(TestObject anchor)
	{
		return vp("POCreated_old2", anchor);
	}
	
	/**
	 * Locate and return the verification point POList_01 object in the SUT.
	 */
	protected IFtVerificationPoint POList_01VP() 
	{
		return vp("POList_01");
	}
	protected IFtVerificationPoint POList_01VP(TestObject anchor)
	{
		return vp("POList_01", anchor);
	}
	
	/**
	 * Locate and return the verification point POList_02 object in the SUT.
	 */
	protected IFtVerificationPoint POList_02VP() 
	{
		return vp("POList_02");
	}
	protected IFtVerificationPoint POList_02VP(TestObject anchor)
	{
		return vp("POList_02", anchor);
	}
	
	/**
	 * Locate and return the verification point Status_53 object in the SUT.
	 */
	protected IFtVerificationPoint Status_53VP() 
	{
		return vp("Status_53");
	}
	protected IFtVerificationPoint Status_53VP(TestObject anchor)
	{
		return vp("Status_53", anchor);
	}
	
	/**
	 * Locate and return the verification point Status_53_01 object in the SUT.
	 */
	protected IFtVerificationPoint Status_53_01VP() 
	{
		return vp("Status_53_01");
	}
	protected IFtVerificationPoint Status_53_01VP(TestObject anchor)
	{
		return vp("Status_53_01", anchor);
	}
	
	/**
	 * Locate and return the verification point StdShipping object in the SUT.
	 */
	protected IFtVerificationPoint StdShippingVP() 
	{
		return vp("StdShipping");
	}
	protected IFtVerificationPoint StdShippingVP(TestObject anchor)
	{
		return vp("StdShipping", anchor);
	}
	
	

	protected TC01_BookPurchaseWValidCCHelper()
	{
		setScriptName("sap_scripts.physical.TC01_BookPurchaseWValidCC");
	}
	
}

