// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sap_scripts.physical;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC02_BookPurchaseWExpressShipping</b><br>
 * Generated     : <b>2013/12/26 2:54:58 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  December 26, 2013
 * @author zsadeque
 */
public abstract class TC02_BookPurchaseWExpressShippingHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point BilledAndAccountingDocCreated object in the SUT.
	 */
	protected IFtVerificationPoint BilledAndAccountingDocCreatedVP() 
	{
		return vp("BilledAndAccountingDocCreated");
	}
	protected IFtVerificationPoint BilledAndAccountingDocCreatedVP(TestObject anchor)
	{
		return vp("BilledAndAccountingDocCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point CC_Status_AB object in the SUT.
	 */
	protected IFtVerificationPoint CC_Status_ABVP() 
	{
		return vp("CC_Status_AB");
	}
	protected IFtVerificationPoint CC_Status_ABVP(TestObject anchor)
	{
		return vp("CC_Status_AB", anchor);
	}
	
	/**
	 * Locate and return the verification point CC_Status_LA_AB object in the SUT.
	 */
	protected IFtVerificationPoint CC_Status_LA_ABVP() 
	{
		return vp("CC_Status_LA_AB");
	}
	protected IFtVerificationPoint CC_Status_LA_ABVP(TestObject anchor)
	{
		return vp("CC_Status_LA_AB", anchor);
	}
	
	/**
	 * Locate and return the verification point DocumentSaved object in the SUT.
	 */
	protected IFtVerificationPoint DocumentSavedVP() 
	{
		return vp("DocumentSaved");
	}
	protected IFtVerificationPoint DocumentSavedVP(TestObject anchor)
	{
		return vp("DocumentSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point empty object in the SUT.
	 */
	protected IFtVerificationPoint emptyVP() 
	{
		return vp("empty");
	}
	protected IFtVerificationPoint emptyVP(TestObject anchor)
	{
		return vp("empty", anchor);
	}
	
	/**
	 * Locate and return the verification point EmptyConfirmTable object in the SUT.
	 */
	protected IFtVerificationPoint EmptyConfirmTableVP() 
	{
		return vp("EmptyConfirmTable");
	}
	protected IFtVerificationPoint EmptyConfirmTableVP(TestObject anchor)
	{
		return vp("EmptyConfirmTable", anchor);
	}
	
	/**
	 * Locate and return the verification point ExpShipping object in the SUT.
	 */
	protected IFtVerificationPoint ExpShippingVP() 
	{
		return vp("ExpShipping");
	}
	protected IFtVerificationPoint ExpShippingVP(TestObject anchor)
	{
		return vp("ExpShipping", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosedVP() 
	{
		return vp("OrderClosed");
	}
	protected IFtVerificationPoint OrderClosedVP(TestObject anchor)
	{
		return vp("OrderClosed", anchor);
	}
	
	/**
	 * Locate and return the verification point orderTable object in the SUT.
	 */
	protected IFtVerificationPoint orderTableVP() 
	{
		return vp("orderTable");
	}
	protected IFtVerificationPoint orderTableVP(TestObject anchor)
	{
		return vp("orderTable", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbdDeliveryCreated object in the SUT.
	 */
	protected IFtVerificationPoint OutbdDeliveryCreatedVP() 
	{
		return vp("OutbdDeliveryCreated");
	}
	protected IFtVerificationPoint OutbdDeliveryCreatedVP(TestObject anchor)
	{
		return vp("OutbdDeliveryCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreated_old object in the SUT.
	 */
	protected IFtVerificationPoint POCreated_oldVP() 
	{
		return vp("POCreated_old");
	}
	protected IFtVerificationPoint POCreated_oldVP(TestObject anchor)
	{
		return vp("POCreated_old", anchor);
	}
	
	/**
	 * Locate and return the verification point POList_01 object in the SUT.
	 */
	protected IFtVerificationPoint POList_01VP() 
	{
		return vp("POList_01");
	}
	protected IFtVerificationPoint POList_01VP(TestObject anchor)
	{
		return vp("POList_01", anchor);
	}
	
	/**
	 * Locate and return the verification point POList_02 object in the SUT.
	 */
	protected IFtVerificationPoint POList_02VP() 
	{
		return vp("POList_02");
	}
	protected IFtVerificationPoint POList_02VP(TestObject anchor)
	{
		return vp("POList_02", anchor);
	}
	
	/**
	 * Locate and return the verification point Status_53 object in the SUT.
	 */
	protected IFtVerificationPoint Status_53VP() 
	{
		return vp("Status_53");
	}
	protected IFtVerificationPoint Status_53VP(TestObject anchor)
	{
		return vp("Status_53", anchor);
	}
	
	

	protected TC02_BookPurchaseWExpressShippingHelper()
	{
		setScriptName("sap_scripts.physical.TC02_BookPurchaseWExpressShipping");
	}
	
}

