// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sap_scripts.physical;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC05_DevicePurchaseWExpShipping</b><br>
 * Generated     : <b>2013/10/04 11:39:20 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  October 04, 2013
 * @author zsadeque
 */
public abstract class TC05_DevicePurchaseWExpShippingHelper extends framework.AtlasScriptbase
{
	/**
	 * Locate and return the verification point BilledAndAccountingDocCreated object in the SUT.
	 */
	protected IFtVerificationPoint BilledAndAccountingDocCreatedVP() 
	{
		return vp("BilledAndAccountingDocCreated");
	}
	protected IFtVerificationPoint BilledAndAccountingDocCreatedVP(TestObject anchor)
	{
		return vp("BilledAndAccountingDocCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point Closed object in the SUT.
	 */
	protected IFtVerificationPoint ClosedVP() 
	{
		return vp("Closed");
	}
	protected IFtVerificationPoint ClosedVP(TestObject anchor)
	{
		return vp("Closed", anchor);
	}
	
	/**
	 * Locate and return the verification point Completed object in the SUT.
	 */
	protected IFtVerificationPoint CompletedVP() 
	{
		return vp("Completed");
	}
	protected IFtVerificationPoint CompletedVP(TestObject anchor)
	{
		return vp("Completed", anchor);
	}
	
	/**
	 * Locate and return the verification point DeviceHistoryOrder object in the SUT.
	 */
	protected IFtVerificationPoint DeviceHistoryOrderVP() 
	{
		return vp("DeviceHistoryOrder");
	}
	protected IFtVerificationPoint DeviceHistoryOrderVP(TestObject anchor)
	{
		return vp("DeviceHistoryOrder", anchor);
	}
	
	/**
	 * Locate and return the verification point DocumentSaved object in the SUT.
	 */
	protected IFtVerificationPoint DocumentSavedVP() 
	{
		return vp("DocumentSaved");
	}
	protected IFtVerificationPoint DocumentSavedVP(TestObject anchor)
	{
		return vp("DocumentSaved", anchor);
	}
	
	/**
	 * Locate and return the verification point empty object in the SUT.
	 */
	protected IFtVerificationPoint emptyVP() 
	{
		return vp("empty");
	}
	protected IFtVerificationPoint emptyVP(TestObject anchor)
	{
		return vp("empty", anchor);
	}
	
	/**
	 * Locate and return the verification point ExpShipping object in the SUT.
	 */
	protected IFtVerificationPoint ExpShippingVP() 
	{
		return vp("ExpShipping");
	}
	protected IFtVerificationPoint ExpShippingVP(TestObject anchor)
	{
		return vp("ExpShipping", anchor);
	}
	
	/**
	 * Locate and return the verification point NoError object in the SUT.
	 */
	protected IFtVerificationPoint NoErrorVP() 
	{
		return vp("NoError");
	}
	protected IFtVerificationPoint NoErrorVP(TestObject anchor)
	{
		return vp("NoError", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderAcknNInboundDel object in the SUT.
	 */
	protected IFtVerificationPoint OrderAcknNInboundDelVP() 
	{
		return vp("OrderAcknNInboundDel");
	}
	protected IFtVerificationPoint OrderAcknNInboundDelVP(TestObject anchor)
	{
		return vp("OrderAcknNInboundDel", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderAcknowledged object in the SUT.
	 */
	protected IFtVerificationPoint OrderAcknowledgedVP() 
	{
		return vp("OrderAcknowledged");
	}
	protected IFtVerificationPoint OrderAcknowledgedVP(TestObject anchor)
	{
		return vp("OrderAcknowledged", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderClosed object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosedVP() 
	{
		return vp("OrderClosed");
	}
	protected IFtVerificationPoint OrderClosedVP(TestObject anchor)
	{
		return vp("OrderClosed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderSourced object in the SUT.
	 */
	protected IFtVerificationPoint OrderSourcedVP() 
	{
		return vp("OrderSourced");
	}
	protected IFtVerificationPoint OrderSourcedVP(TestObject anchor)
	{
		return vp("OrderSourced", anchor);
	}
	
	/**
	 * Locate and return the verification point OutbdDeliveryCreated object in the SUT.
	 */
	protected IFtVerificationPoint OutbdDeliveryCreatedVP() 
	{
		return vp("OutbdDeliveryCreated");
	}
	protected IFtVerificationPoint OutbdDeliveryCreatedVP(TestObject anchor)
	{
		return vp("OutbdDeliveryCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point POCreated object in the SUT.
	 */
	protected IFtVerificationPoint POCreatedVP() 
	{
		return vp("POCreated");
	}
	protected IFtVerificationPoint POCreatedVP(TestObject anchor)
	{
		return vp("POCreated", anchor);
	}
	
	/**
	 * Locate and return the verification point POList_01 object in the SUT.
	 */
	protected IFtVerificationPoint POList_01VP() 
	{
		return vp("POList_01");
	}
	protected IFtVerificationPoint POList_01VP(TestObject anchor)
	{
		return vp("POList_01", anchor);
	}
	
	/**
	 * Locate and return the verification point POList_02 object in the SUT.
	 */
	protected IFtVerificationPoint POList_02VP() 
	{
		return vp("POList_02");
	}
	protected IFtVerificationPoint POList_02VP(TestObject anchor)
	{
		return vp("POList_02", anchor);
	}
	
	/**
	 * Locate and return the verification point ShipConfirm object in the SUT.
	 */
	protected IFtVerificationPoint ShipConfirmVP() 
	{
		return vp("ShipConfirm");
	}
	protected IFtVerificationPoint ShipConfirmVP(TestObject anchor)
	{
		return vp("ShipConfirm", anchor);
	}
	
	/**
	 * Locate and return the verification point Status_53 object in the SUT.
	 */
	protected IFtVerificationPoint Status_53VP() 
	{
		return vp("Status_53");
	}
	protected IFtVerificationPoint Status_53VP(TestObject anchor)
	{
		return vp("Status_53", anchor);
	}
	
	

	protected TC05_DevicePurchaseWExpShippingHelper()
	{
		setScriptName("sap_scripts.physical.TC05_DevicePurchaseWExpShipping");
	}
	
}

