// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.sap_scripts.physical;
import framework.AtlasScriptbase;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TC06_PurchaseNewMembership</b><br>
 * Generated     : <b>2013/10/07 11:49:24 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  October 07, 2013
 * @author zsadeque
 */
public abstract class TC06_PurchaseNewMembershipHelper extends framework.AtlasScriptbase
{
	/**
	 * KOMFKVBELN: with default state.
	 *		Name : KOMFK-VBELN
	 * 		Id : /ctxtKOMFK-VBELN[0,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Document
	 */
	protected SAPGuiTextTestObject text_komfkvbeln() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_komfkvbeln"));
	}
	/**
	 * KOMFKVBELN: with specific test context and state.
	 *		Name : KOMFK-VBELN
	 * 		Id : /ctxtKOMFK-VBELN[0,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Document
	 */
	protected SAPGuiTextTestObject text_komfkvbeln(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_komfkvbeln"), anchor, flags);
	}
	
	/**
	 * CreateBillingDocument: with default state.
	 *		Name : wnd[0]
	 * 		Text : Create Billing Document
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_createBillingDocument() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_createBillingDocument"));
	}
	/**
	 * CreateBillingDocument: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : Create Billing Document
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_createBillingDocument(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_createBillingDocument"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point OrderClosed object in the SUT.
	 */
	protected IFtVerificationPoint OrderClosedVP() 
	{
		return vp("OrderClosed");
	}
	protected IFtVerificationPoint OrderClosedVP(TestObject anchor)
	{
		return vp("OrderClosed", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderEmails object in the SUT.
	 */
	protected IFtVerificationPoint OrderEmailsVP() 
	{
		return vp("OrderEmails");
	}
	protected IFtVerificationPoint OrderEmailsVP(TestObject anchor)
	{
		return vp("OrderEmails", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderEntered object in the SUT.
	 */
	protected IFtVerificationPoint OrderEnteredVP() 
	{
		return vp("OrderEntered");
	}
	protected IFtVerificationPoint OrderEnteredVP(TestObject anchor)
	{
		return vp("OrderEntered", anchor);
	}
	
	

	protected TC06_PurchaseNewMembershipHelper()
	{
		setScriptName("sap_scripts.physical.TC06_PurchaseNewMembership");
	}
	
}

